apiVersion: apps/v
kind: Deployment
metadata:
  name: deployment-fe-app-2
  labels:
    app: nginx
    env: dev
spec:
  strategy:
    type: Recreate
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      env: dev
  template:
    metadata:
      labels:
        app: nginx
        env: dev
    spec:
      containers:
        - name: nginx
          image: devopsdecode/april-2025:v1
          ports:
            - containerPort: 80
        - name: monitoring-pod-exporter
          image: quay.io/prometheus/node-exporter:latest
          ports: 9100
