#AKMS
apiVersion: app/v1
kind: replicaset
metadata:
  name: nginx-replicaset
  labels:
    app: nginx-replicaset
    env: dev
  spec:
    replicas: 
    selector: 
      matchLabels:
        app: nginx
        env: dev
    template:
      metadata:
      name: nginx-pod
      labels: 
        app: nginx
        env: dev
      spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
        - name: monitoring-pod-exporter
          image: quay.io/prometheus/node-exporter:latest
          ports:
            - containerPort: 9100
